class CustomerNotFoundError(Exception):
    pass

class CustomerAlreadyExistsError(Exception):
    pass